version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-web:latest
    container_name: web-pomogite
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
      MYSQL_HOST: app_mysql

  db:
    image: mysql:8.0
    container_name: app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./src/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/sql/dampa:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
